# simpan config baru
nano ~/devops-monitoring-stack/configs/nginx/nginx.conf
# paste isi:
events {
  worker_connections 1024;
}
http {
  default_type text/plain;
  server {
    listen 0.0.0.0:8080;
    server_name _;
    location / { return 200 "hello from nginx\n"; }
    location /stub_status {
      stub_status;
      access_log off;
      allow 127.0.0.1;
      allow 172.16.0.0/12;
      deny all;
    }
  }
}

