server {
    listen 0.0.0.0:8080;
    server_name _;

    location /stub_status {
        stub_status;
        access_log off;
        allow 127.0.0.1;
        allow 172.16.0.0/12;  # jaringan docker bridge
        deny all;
    }
}
