name: CI

on:
  push:
    branches:
      - main
      - pipeline-upgrade
  pull_request:
    branches:
      - main

jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Workflow triggers work!"
